/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author chrispeterkins
 */
public class SetupForm extends javax.swing.JPanel {

    /**
     * Creates new form SetupForm
     */
    public SetupForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WhereToClickButtons = new javax.swing.ButtonGroup();
        HowManyClicksButtons = new javax.swing.ButtonGroup();
        clickTypeButtons = new javax.swing.ButtonGroup();
        clickDelayButtons = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        WhereToClickPanel = new javax.swing.JPanel();
        whereverMouseClicksButton = new javax.swing.JRadioButton();
        randomDekstopMouseClicksButton = new javax.swing.JRadioButton();
        RandomRectangleMouseClicksButton = new javax.swing.JRadioButton();
        xLabel = new javax.swing.JLabel();
        widthLabel = new javax.swing.JLabel();
        yLabel = new javax.swing.JLabel();
        heightLabel = new javax.swing.JLabel();
        areaSelectButton = new javax.swing.JButton();
        xValueSpinner = new javax.swing.JSpinner();
        widthValueSpinner = new javax.swing.JSpinner();
        yValueSpinner = new javax.swing.JSpinner();
        heightValueSpinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        endlessClicksButton = new javax.swing.JRadioButton();
        definitiveClicksButton = new javax.swing.JRadioButton();
        numberOfClicksSpinner = new javax.swing.JSpinner();
        clicks = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        leftClickButton = new javax.swing.JRadioButton();
        rightClickButton = new javax.swing.JRadioButton();
        middleClickButton = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        randomDelayClicksButton = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        startDelaySpinner = new javax.swing.JSpinner();
        and = new javax.swing.JLabel();
        endDelaySpinner = new javax.swing.JSpinner();
        timeUnitDelayComboBox = new javax.swing.JComboBox<>();
        fixedDelaySpinner = new javax.swing.JSpinner();
        timeUnitFixedComboBox = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        shortCutKeyTextField = new javax.swing.JTextField();
        assignShortcutButton = new javax.swing.JButton();
        clearShortcutButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        WhereToClickPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Where To Click?"));

        WhereToClickButtons.add(whereverMouseClicksButton);
        whereverMouseClicksButton.setText("Wherever Mouse Cursor is when Staring Clicks");

        WhereToClickButtons.add(randomDekstopMouseClicksButton);
        randomDekstopMouseClicksButton.setText("Random Location Anywhere on Total Desktop Area");

        WhereToClickButtons.add(RandomRectangleMouseClicksButton);
        RandomRectangleMouseClicksButton.setText("Random Location within given below Rectangle Area");

        xLabel.setText("X:");

        widthLabel.setText("Width:");

        yLabel.setText("Y:");

        heightLabel.setText("Height:");

        areaSelectButton.setText("...");
        areaSelectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaSelectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout WhereToClickPanelLayout = new javax.swing.GroupLayout(WhereToClickPanel);
        WhereToClickPanel.setLayout(WhereToClickPanelLayout);
        WhereToClickPanelLayout.setHorizontalGroup(
            WhereToClickPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WhereToClickPanelLayout.createSequentialGroup()
                .addGroup(WhereToClickPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(WhereToClickPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(WhereToClickPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RandomRectangleMouseClicksButton)
                            .addComponent(randomDekstopMouseClicksButton)
                            .addComponent(whereverMouseClicksButton)))
                    .addGroup(WhereToClickPanelLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(WhereToClickPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(xLabel)
                            .addComponent(widthLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(WhereToClickPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(widthValueSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(xValueSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(WhereToClickPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WhereToClickPanelLayout.createSequentialGroup()
                                .addComponent(heightLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(heightValueSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(WhereToClickPanelLayout.createSequentialGroup()
                                .addComponent(areaSelectButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yValueSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        WhereToClickPanelLayout.setVerticalGroup(
            WhereToClickPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WhereToClickPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(whereverMouseClicksButton)
                .addGap(18, 18, 18)
                .addComponent(randomDekstopMouseClicksButton)
                .addGap(18, 18, 18)
                .addComponent(RandomRectangleMouseClicksButton)
                .addGap(18, 18, 18)
                .addGroup(WhereToClickPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(areaSelectButton)
                    .addGroup(WhereToClickPanelLayout.createSequentialGroup()
                        .addGroup(WhereToClickPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(xLabel)
                            .addComponent(yLabel)
                            .addComponent(xValueSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yValueSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(WhereToClickPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(widthLabel)
                            .addComponent(widthValueSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(heightLabel)
                            .addComponent(heightValueSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Mouse Cursor at X = ?, Y = ?");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("How Many Clicks to Automate?"));

        HowManyClicksButtons.add(endlessClicksButton);
        endlessClicksButton.setText("Keep on clicking until stopped");

        definitiveClicksButton.setText("Stop clicking after automating");

        clicks.setText("Clicks");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(endlessClicksButton)
                    .addComponent(definitiveClicksButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numberOfClicksSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clicks)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(endlessClicksButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(definitiveClicksButton)
                    .addComponent(numberOfClicksSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clicks))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Select Click Type Here"));

        clickTypeButtons.add(leftClickButton);
        leftClickButton.setText("Left Click");

        clickTypeButtons.add(rightClickButton);
        rightClickButton.setText("Right Click");

        clickTypeButtons.add(middleClickButton);
        middleClickButton.setText("Middle Click");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(leftClickButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightClickButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(middleClickButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leftClickButton)
                    .addComponent(rightClickButton)
                    .addComponent(middleClickButton))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Delay Between Clicks"));

        randomDelayClicksButton.setText("Random Delay Between Clicks");

        jRadioButton2.setText("Fixed Delay Between Clicks");

        and.setText("And");

        timeUnitDelayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        timeUnitFixedComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(randomDelayClicksButton)
                    .addComponent(jRadioButton2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(fixedDelaySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(timeUnitFixedComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(startDelaySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(and)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(endDelaySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(timeUnitDelayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(randomDelayClicksButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startDelaySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(and)
                    .addComponent(endDelaySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeUnitDelayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fixedDelaySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeUnitFixedComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Shortcut Key to Start/Stop Clicking"));

        assignShortcutButton.setText("Assign");
        assignShortcutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignShortcutButtonActionPerformed(evt);
            }
        });

        clearShortcutButton.setText("Clear");
        clearShortcutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearShortcutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(shortCutKeyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(assignShortcutButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearShortcutButton))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shortCutKeyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assignShortcutButton)
                    .addComponent(clearShortcutButton)))
        );

        jLabel2.setText("Total Clickable Area of Width = ?, Height = ?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(WhereToClickPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(236, 236, 236))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WhereToClickPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void areaSelectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaSelectButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areaSelectButtonActionPerformed

    private void assignShortcutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignShortcutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assignShortcutButtonActionPerformed

    private void clearShortcutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearShortcutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearShortcutButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup HowManyClicksButtons;
    private javax.swing.JRadioButton RandomRectangleMouseClicksButton;
    private javax.swing.ButtonGroup WhereToClickButtons;
    private javax.swing.JPanel WhereToClickPanel;
    private javax.swing.JLabel and;
    private javax.swing.JButton areaSelectButton;
    private javax.swing.JButton assignShortcutButton;
    private javax.swing.JButton clearShortcutButton;
    private javax.swing.ButtonGroup clickDelayButtons;
    private javax.swing.ButtonGroup clickTypeButtons;
    private javax.swing.JLabel clicks;
    private javax.swing.JRadioButton definitiveClicksButton;
    private javax.swing.JSpinner endDelaySpinner;
    private javax.swing.JRadioButton endlessClicksButton;
    private javax.swing.JSpinner fixedDelaySpinner;
    private javax.swing.JLabel heightLabel;
    private javax.swing.JSpinner heightValueSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton leftClickButton;
    private javax.swing.JRadioButton middleClickButton;
    private javax.swing.JSpinner numberOfClicksSpinner;
    private javax.swing.JRadioButton randomDekstopMouseClicksButton;
    private javax.swing.JRadioButton randomDelayClicksButton;
    private javax.swing.JRadioButton rightClickButton;
    private javax.swing.JTextField shortCutKeyTextField;
    private javax.swing.JSpinner startDelaySpinner;
    private javax.swing.JComboBox<String> timeUnitDelayComboBox;
    private javax.swing.JComboBox<String> timeUnitFixedComboBox;
    private javax.swing.JRadioButton whereverMouseClicksButton;
    private javax.swing.JLabel widthLabel;
    private javax.swing.JSpinner widthValueSpinner;
    private javax.swing.JLabel xLabel;
    private javax.swing.JSpinner xValueSpinner;
    private javax.swing.JLabel yLabel;
    private javax.swing.JSpinner yValueSpinner;
    // End of variables declaration//GEN-END:variables
}
